#!/usr/bin/env bash
set -euo pipefail

mkdir -p target
echo '#!/bin/bash
set -eux
mkdir -p /root/.gnupg && chmod 600 /root/.gnupg
cp -r /gnupg/* /root/.gnupg/
rm -f /root/.gnupg/S.*
rm -f /root/.gnupg/*.conf
export GPG_TTY=$(tty)

curl -sL https://deb.nodesource.com/setup_12.x | bash
apt install -y nodejs
./lein clean
./lein build-js
./lein deploy clojars
' > target/entrypoint.sh

mkdir -p .release-cache

docker run --rm -ti \
  -v $(cd $(dirname $0) && pwd):/build \
  -v $(cd $(dirname $0) && pwd)/.release-cache:/root/.m2 \
  -v $HOME/.gnupg:/gnupg:ro \
  -w /build \
  openjdk:8-jdk \
  sh target/entrypoint.sh
